// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: direct_organ.proto

package proto_direct_organ

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDirectOrganRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	CrudDates string `protobuf:"bytes,4,opt,name=crud_dates,json=crudDates,proto3" json:"crud_dates,omitempty"`
	CbuCode   int64  `protobuf:"varint,5,opt,name=cbu_code,json=cbuCode,proto3" json:"cbu_code,omitempty"`
}

func (x *CreateDirectOrganRequest) Reset() {
	*x = CreateDirectOrganRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_direct_organ_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDirectOrganRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectOrganRequest) ProtoMessage() {}

func (x *CreateDirectOrganRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_organ_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectOrganRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectOrganRequest) Descriptor() ([]byte, []int) {
	return file_direct_organ_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDirectOrganRequest) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateDirectOrganRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDirectOrganRequest) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *CreateDirectOrganRequest) GetCrudDates() string {
	if x != nil {
		return x.CrudDates
	}
	return ""
}

func (x *CreateDirectOrganRequest) GetCbuCode() int64 {
	if x != nil {
		return x.CbuCode
	}
	return 0
}

type SingleDirectOrganRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SingleDirectOrganRequest) Reset() {
	*x = SingleDirectOrganRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_direct_organ_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleDirectOrganRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleDirectOrganRequest) ProtoMessage() {}

func (x *SingleDirectOrganRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_organ_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleDirectOrganRequest.ProtoReflect.Descriptor instead.
func (*SingleDirectOrganRequest) Descriptor() ([]byte, []int) {
	return file_direct_organ_proto_rawDescGZIP(), []int{1}
}

func (x *SingleDirectOrganRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DirectOrganProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code      int64  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,4,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	CrudDates string `protobuf:"bytes,5,opt,name=crud_dates,json=crudDates,proto3" json:"crud_dates,omitempty"`
	CbuCode   int64  `protobuf:"varint,6,opt,name=cbu_code,json=cbuCode,proto3" json:"cbu_code,omitempty"`
}

func (x *DirectOrganProfileResponse) Reset() {
	*x = DirectOrganProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_direct_organ_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectOrganProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectOrganProfileResponse) ProtoMessage() {}

func (x *DirectOrganProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_direct_organ_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectOrganProfileResponse.ProtoReflect.Descriptor instead.
func (*DirectOrganProfileResponse) Descriptor() ([]byte, []int) {
	return file_direct_organ_proto_rawDescGZIP(), []int{2}
}

func (x *DirectOrganProfileResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DirectOrganProfileResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DirectOrganProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectOrganProfileResponse) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *DirectOrganProfileResponse) GetCrudDates() string {
	if x != nil {
		return x.CrudDates
	}
	return ""
}

func (x *DirectOrganProfileResponse) GetCbuCode() int64 {
	if x != nil {
		return x.CbuCode
	}
	return 0
}

type SuccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_direct_organ_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_direct_organ_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_direct_organ_proto_rawDescGZIP(), []int{3}
}

func (x *SuccessResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type UpdateDirectOrganRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code      int64  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,4,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	CrudDates string `protobuf:"bytes,5,opt,name=crud_dates,json=crudDates,proto3" json:"crud_dates,omitempty"`
	CbuCode   int64  `protobuf:"varint,6,opt,name=cbu_code,json=cbuCode,proto3" json:"cbu_code,omitempty"`
}

func (x *UpdateDirectOrganRequest) Reset() {
	*x = UpdateDirectOrganRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_direct_organ_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDirectOrganRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDirectOrganRequest) ProtoMessage() {}

func (x *UpdateDirectOrganRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_organ_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDirectOrganRequest.ProtoReflect.Descriptor instead.
func (*UpdateDirectOrganRequest) Descriptor() ([]byte, []int) {
	return file_direct_organ_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDirectOrganRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDirectOrganRequest) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateDirectOrganRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDirectOrganRequest) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *UpdateDirectOrganRequest) GetCrudDates() string {
	if x != nil {
		return x.CrudDates
	}
	return ""
}

func (x *UpdateDirectOrganRequest) GetCbuCode() int64 {
	if x != nil {
		return x.CbuCode
	}
	return 0
}

var File_direct_organ_proto protoreflect.FileDescriptor

var file_direct_organ_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x75, 0x64,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x75, 0x64, 0x44, 0x61, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x62, 0x75, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x62, 0x75, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xad,
	0x01, 0x0a, 0x1a, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x75, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x62, 0x75, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x62, 0x75, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x2d,
	0x0a, 0x0f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xab, 0x01,
	0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x72,
	0x67, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x75, 0x64, 0x44, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x62, 0x75, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x63, 0x62, 0x75, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x84, 0x02, 0x0a, 0x12,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x4f, 0x72, 0x67, 0x61, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x19, 0x2e, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x4f, 0x72, 0x67, 0x61, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x67,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_direct_organ_proto_rawDescOnce sync.Once
	file_direct_organ_proto_rawDescData = file_direct_organ_proto_rawDesc
)

func file_direct_organ_proto_rawDescGZIP() []byte {
	file_direct_organ_proto_rawDescOnce.Do(func() {
		file_direct_organ_proto_rawDescData = protoimpl.X.CompressGZIP(file_direct_organ_proto_rawDescData)
	})
	return file_direct_organ_proto_rawDescData
}

var file_direct_organ_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_direct_organ_proto_goTypes = []interface{}{
	(*CreateDirectOrganRequest)(nil),   // 0: CreateDirectOrganRequest
	(*SingleDirectOrganRequest)(nil),   // 1: SingleDirectOrganRequest
	(*DirectOrganProfileResponse)(nil), // 2: DirectOrganProfileResponse
	(*SuccessResponse)(nil),            // 3: SuccessResponse
	(*UpdateDirectOrganRequest)(nil),   // 4: UpdateDirectOrganRequest
}
var file_direct_organ_proto_depIdxs = []int32{
	0, // 0: DirectOrganService.Create:input_type -> CreateDirectOrganRequest
	1, // 1: DirectOrganService.Read:input_type -> SingleDirectOrganRequest
	4, // 2: DirectOrganService.Update:input_type -> UpdateDirectOrganRequest
	1, // 3: DirectOrganService.Delete:input_type -> SingleDirectOrganRequest
	2, // 4: DirectOrganService.Create:output_type -> DirectOrganProfileResponse
	2, // 5: DirectOrganService.Read:output_type -> DirectOrganProfileResponse
	3, // 6: DirectOrganService.Update:output_type -> SuccessResponse
	3, // 7: DirectOrganService.Delete:output_type -> SuccessResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_direct_organ_proto_init() }
func file_direct_organ_proto_init() {
	if File_direct_organ_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_direct_organ_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDirectOrganRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_direct_organ_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleDirectOrganRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_direct_organ_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectOrganProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_direct_organ_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_direct_organ_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDirectOrganRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_direct_organ_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_direct_organ_proto_goTypes,
		DependencyIndexes: file_direct_organ_proto_depIdxs,
		MessageInfos:      file_direct_organ_proto_msgTypes,
	}.Build()
	File_direct_organ_proto = out.File
	file_direct_organ_proto_rawDesc = nil
	file_direct_organ_proto_goTypes = nil
	file_direct_organ_proto_depIdxs = nil
}
