// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: bank_branch.proto

package bank_branch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BankBranchServiceClient is the client API for BankBranchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankBranchServiceClient interface {
	Create(ctx context.Context, in *CreateBankBranchRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	Read(ctx context.Context, in *SingleBankBranchRequest, opts ...grpc.CallOption) (*BankBranchProfileResponse, error)
	Update(ctx context.Context, in *SingleBankBranchRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	Delete(ctx context.Context, in *SingleBankBranchRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type bankBranchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankBranchServiceClient(cc grpc.ClientConnInterface) BankBranchServiceClient {
	return &bankBranchServiceClient{cc}
}

func (c *bankBranchServiceClient) Create(ctx context.Context, in *CreateBankBranchRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/BankBranchService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankBranchServiceClient) Read(ctx context.Context, in *SingleBankBranchRequest, opts ...grpc.CallOption) (*BankBranchProfileResponse, error) {
	out := new(BankBranchProfileResponse)
	err := c.cc.Invoke(ctx, "/BankBranchService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankBranchServiceClient) Update(ctx context.Context, in *SingleBankBranchRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/BankBranchService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankBranchServiceClient) Delete(ctx context.Context, in *SingleBankBranchRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/BankBranchService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankBranchServiceServer is the server API for BankBranchService service.
// All implementations must embed UnimplementedBankBranchServiceServer
// for forward compatibility
type BankBranchServiceServer interface {
	Create(context.Context, *CreateBankBranchRequest) (*SuccessResponse, error)
	Read(context.Context, *SingleBankBranchRequest) (*BankBranchProfileResponse, error)
	Update(context.Context, *SingleBankBranchRequest) (*SuccessResponse, error)
	Delete(context.Context, *SingleBankBranchRequest) (*SuccessResponse, error)
	mustEmbedUnimplementedBankBranchServiceServer()
}

// UnimplementedBankBranchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBankBranchServiceServer struct {
}

func (UnimplementedBankBranchServiceServer) Create(context.Context, *CreateBankBranchRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBankBranchServiceServer) Read(context.Context, *SingleBankBranchRequest) (*BankBranchProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedBankBranchServiceServer) Update(context.Context, *SingleBankBranchRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBankBranchServiceServer) Delete(context.Context, *SingleBankBranchRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBankBranchServiceServer) mustEmbedUnimplementedBankBranchServiceServer() {}

// UnsafeBankBranchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankBranchServiceServer will
// result in compilation errors.
type UnsafeBankBranchServiceServer interface {
	mustEmbedUnimplementedBankBranchServiceServer()
}

func RegisterBankBranchServiceServer(s grpc.ServiceRegistrar, srv BankBranchServiceServer) {
	s.RegisterService(&BankBranchService_ServiceDesc, srv)
}

func _BankBranchService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBankBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankBranchServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BankBranchService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankBranchServiceServer).Create(ctx, req.(*CreateBankBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankBranchService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleBankBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankBranchServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BankBranchService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankBranchServiceServer).Read(ctx, req.(*SingleBankBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankBranchService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleBankBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankBranchServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BankBranchService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankBranchServiceServer).Update(ctx, req.(*SingleBankBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankBranchService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleBankBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankBranchServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BankBranchService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankBranchServiceServer).Delete(ctx, req.(*SingleBankBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankBranchService_ServiceDesc is the grpc.ServiceDesc for BankBranchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankBranchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BankBranchService",
	HandlerType: (*BankBranchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BankBranchService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _BankBranchService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BankBranchService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BankBranchService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank_branch.proto",
}
